Description: This template contains the DynamoDB table required by our entire stack.

Parameters: 

  #+------------------------------------------------------------------
  #|  File VPC.yaml
  #+------------------------------------------------------------------

  #-------------
  # DynamoDB
  TableName:
    Description: The table name in database
    Type: String
    Default: joseph-table

  #+------------------------------------------------------------------
  #|  Bucket name
  #+------------------------------------------------------------------

  BucketName:
    Description: Bucket name where the templates are located
    Type: String
    Default: joseph-templates.s3-us-west-2.amazonaws.com


  #+------------------------------------------------------------------
  #| Name api
  #+------------------------------------------------------------------

  ApiName:
    Type: String
    Default: joseph_api
    Description: creation of api

  lambdaFunctionName:
    Type: "String"
    Description: Name function lambda
    Default: "my-function"

Resources:

  #-------------
  # DB
  DynamoDB:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        TableName: !Ref TableName
      TemplateURL: !Sub https://${BucketName}/Ejercicio_Lambda/DB/Dynamo.yaml 
  #+------------------------------------------------------------------
  #|  Lambda
  #+------------------------------------------------------------------

  #-------------
  # Lambda

  lambdaFunction:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        TableName: !Ref TableName
      TemplateURL: !Sub https://${BucketName}/Ejercicio_Lambda/Lambda/lambda.yaml 


  #-------------
  # Api Gateway  
  ApiGateway:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ApiName: !Ref ApiName
        ArnGetFunction: !GetAtt 'lambdaFunction.Outputs.ArnGetFunction'
        ArnPostFunction: !GetAtt 'lambdaFunction.Outputs.ArnPostFunction'
        ArnDeleteFunction: !GetAtt 'lambdaFunction.Outputs.ArnDeleteFunction'
      TemplateURL: !Sub https://${BucketName}/Ejercicio_Lambda/Api/api.yaml 