Description:  This template contains the Api Gateway


Parameters:
  ApiName:
    Type: String
    Default: joseph_api
    Description: creation of api

  ArnGetFunction:
    Type: "String"
    Description: Arn lambda function insert

Resources:

  CustomerApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties: 
      Name: !Ref ApiName
      
    
 
  apiGatewayRootMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      AuthorizationType: "NONE"
      HttpMethod: "GET"
      Integration:
        ConnectionType: INTERNET
        IntegrationHttpMethod: "GET"
        Type: "AWS_PROXY"
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2019-09-23/functions/${ArnGetFunction}/invocations"
      ResourceId: !GetAtt "CustomerApi.RootResourceId"
      RestApiId: !Ref "CustomerApi"

  apiGatewayDeployment:
    Type: "AWS::ApiGateway::Deployment"
    DependsOn:
      - "apiGatewayRootMethod"
    Properties:
      RestApiId: !Ref "CustomerApi"
      StageName: test1

      
  lambdaApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref ArnGetFunction
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ArnGetFunction}/*/GET/"